export const BUY_COFFEE = 'BUY_COFFEE'
export const BUY_BIKE = 'BUY_BIKE'
export const BUY_CAR = 'BUY_CAR'
export const BUY_ITEM = 'BUY_ITEM'
export const TRANSFER = 'TRANSFER'
export const SALARY = 'SALARY'